# Generated by Django 5.0.8 on 2024-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('student_id', models.IntegerField(primary_key='true', serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('student_contact', models.IntegerField()),
                ('student_image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
